name: wabiz_freezed
description: "wabiz freezed"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
